# Generated by Django 3.1.5 on 2021-05-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_covid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry', models.IntegerField()),
                ('fever', models.IntegerField()),
                ('throat', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('predict', models.IntegerField()),
            ],
        ),
    ]
