# Generated by Django 3.1.5 on 2021-05-21 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_delete_covid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry', models.IntegerField()),
                ('fever', models.IntegerField()),
                ('throat', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('predict', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
