# Generated by Django 3.1.5 on 2021-05-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_covid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='predict',
        ),
    ]
